name: SonarQube Analysis
on:
  pull_request:
    branches:
      - '*'
jobs:
  sonarcube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Analysis
        uses: ./.github/actions/sonar-analysis
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: andreevich404_Chat
          organization: ivan-andreevich
          host-url: https://sonarcloud.io
          binaries-path: chat-server/target/classes,chat-client/target/classes