name: SonarQube Analysis
on:
  pull_request:
    branches:
      - '*'
jobs:
  sonarcube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build and analyze with Maven
        run: |
          mvn clean verify \
            -DskipTests=false \
            -Dsonar.projectKey=andreevich404_Chat \
            -Dsonar.organization=ivan-andreevich \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=chat-server/src,chat-client/src \
            -Dsonar.java.binaries=chat-server/target/classes,chat-client/target/classes \
            -Dsonar.java.libraries=chat-server/target/*.jar,chat-client/target/*.jar \
            sonar:sonar
        shell: bash